sudo: false
osx_image: xcode7.2
language: objective-c
env:
  global:
    - IOS_SDK=iphonesimulator9.2
    - TVOS_SDK=appletvsimulator9.1
    - OSX_SDK=macosx10.11
  matrix:
      - DESTINATION="OS=9.2,name=iPad 2"         SDK="$IOS_SDK"
      - DESTINATION="OS=9.2,name=iPad Air"       SDK="$IOS_SDK"
      - DESTINATION="OS=9.2,name=iPhone 5"       SDK="$IOS_SDK"
      - DESTINATION="OS=9.2,name=iPhone 6s"      SDK="$IOS_SDK"
      - DESTINATION="OS=8.4,name=iPhone 6"       SDK="$IOS_SDK"
      - DESTINATION="OS=8.4,name=iPad Air"       SDK="$IOS_SDK"
      - DESTINATION="OS=9.1,name=Apple TV 1080p" SDK="$TVOS_SDK"
      - DESTINATION="arch=x86_64"                SDK="$OSX_SDK"

script:
    - set -o pipefail
    - xcodebuild -version
    - xcodebuild -scheme "Transporter" -configuration Debug -sdk "$SDK" -destination "$DESTINATION" test -enableCodeCoverage YES  "IDEBuildOperationMaxNumberOfConcurrentCompileTasks=`sysctl -n hw.ncpu`" | xcpretty

after_success:
    - bash <(curl -s https://codecov.io/bash)
