language: objective-c
sudo: false
os: osx
osx_image: xcode10.2

matrix:
  include:
    - env: ACTION=test_ios12
    - env: ACTION=test_ios11
    - env: ACTION=test_tvos12
    - env: ACTION=test_tvos11
    - env: ACTION=test_ios_swift4
    - env: ACTION=test_tvos_swift4
    - env: ACTION=test_macos
    - env: ACTION=build_watchos
    - env: ACTION=pod_lint
    - env: ACTION=carthage_build
    # - os: osx
    #   env: ACTION=spm_macos

script:
  - bundle exec fastlane $ACTION
